os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      texinfo

language: cpp
git:
  submodules: true

script:
  - cd JustAnotherVoiceChat.Server
  - mkdir build
  - cd build
  - cmake ..
  - make
