os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      texinfo

language: cpp
git:
  submodules: false

before_install:
  - git config --global http.sslVerify "false"
  - git submodule update --init --recursive
  - git config --global http.sslVerify "true"

script:
  - cd JustAnotherVoiceChat.Server
  - mkdir build
  - cd build
  - cmake ..
  - make
